import { motion, AnimatePresence } from "framer-motion";
import { ArrowRight, FileText, Layers, Globe, Sparkles, Zap, Download, CheckCircle2, ShieldCheck, ChevronDown, Award, Users, Activity, Sliders } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { useAuth } from "@/contexts/use-auth";
import ThemeToggle from "@/components/ThemeToggle";
import { useState } from "react";

// ==========================================
// CONSTANTS & ANIMATIONS
// ==========================================
const features = [
  { icon: FileText, title: "Smart Resume Parsing", desc: "Upload PDF, DOCX, TXT, TEX, or image resumes and auto-extract profile-ready data seamlessly." },
  { icon: Sparkles, title: "AI-Powered Tailoring", desc: "Paste a job description and get a perfectly matched resume tailored specifically to job keywords in seconds." },
  { icon: Layers, title: "Project Portfolio", desc: "Add projects manually or import directly from GitHub README files to keep your profile current." },
  { icon: Globe, title: "Cloudflare Portfolio Deploy", desc: "Generate and publish your portfolio to Cloudflare Pages with custom domain support." },
  { icon: Zap, title: "GitHub Source Export", desc: "Export generated portfolio source code directly to GitHub when you need granular code control." },
  { icon: Download, title: "Instant Resume Export", desc: "Save tailored results as master resumes and export polished resume previews as PDF." },
];

const steps = [
  { step: "01", title: "Upload Master Profile", desc: "Extract complete profile data from your existing resume." },
  { step: "02", title: "AI Job Tailoring", desc: "Analyze job description & optimize keywords instantly." },
  { step: "03", title: "One-Click Deploy", desc: "Publish a live high-speed portfolio link on Cloudflare." }
];

const stats = [
  { value: "10,000+", label: "Resumes Tailored", icon: FileText },
  { value: "99.4%", label: "ATS Pass Rate", icon: Award },
  { value: "< 2.5s", label: "AI Tailor Speed", icon: Activity },
  { value: "100%", label: "Cloudflare Uptime", icon: Globe }
];

const sampleRoles = [
  {
    role: "Senior Fullstack Engineer",
    matchScore: 98,
    keywords: ["React 18", "TypeScript", "Node.js", "GraphQL", "PostgreSQL", "Docker", "TailwindCSS"]
  },
  {
    role: "AI & ML Solutions Lead",
    matchScore: 96,
    keywords: ["Python", "PyTorch", "LLM Fine-tuning", "RAG Pipeline", "Vector DB", "FastAPI"]
  },
  {
    role: "DevOps & Cloud Architect",
    matchScore: 99,
    keywords: ["Kubernetes", "AWS Terraform", "CI/CD Pipeline", "Cloudflare Pages", "Prometheus"]
  }
];

const faqs = [
  {
    q: "How does the AI tailoring process work?",
    a: "Our system parses your uploaded master profile and compares it against the target job description. The AI rewrites bullet points, highlights matching technical skills, and structures ATS-friendly sections while maintaining full factual accuracy."
  },
  {
    q: "Can I deploy portfolios with my own custom domain?",
    a: "Yes! Portfolios generated by ResumeAI are published directly to Cloudflare Pages. You can use your default Cloudflare link or bind any custom domain in your portfolio settings."
  },
  {
    q: "What file formats are supported for resume upload?",
    a: "ResumeAI supports PDF, DOCX, TXT, TEX, and image files (PNG/JPEG) via high-accuracy optical character recognition (OCR) and document parsing."
  },
  {
    q: "Can I export source code to GitHub?",
    a: "Absolutely! You can export the generated portfolio's React / HTML source directly to your GitHub repository with one click."
  }
];

const containerVariants = {
  hidden: { opacity: 0 },
  visible: { opacity: 1, transition: { staggerChildren: 0.12 } },
};

const cardVariants = {
  hidden: { opacity: 0, y: 35, scale: 0.96 },
  visible: { opacity: 1, y: 0, scale: 1, transition: { duration: 0.5, ease: [0.22, 1, 0.36, 1] } },
};

// ==========================================
// MAIN COMPONENT
// ==========================================
const Landing = () => {
  const navigate = useNavigate();
  const { signInWithGoogle, loading, firebaseUser } = useAuth();
  const [selectedRoleIdx, setSelectedRoleIdx] = useState(0);
  const [openFaqIdx, setOpenFaqIdx] = useState<number | null>(0);

  const handleAuthClick = async () => {
    try {
      await signInWithGoogle();
      navigate("/dashboard");
    } catch {
      toast.error("Sign-in failed. Check your Firebase provider settings.");
    }
  };

  const handleGetStarted = async () => {
    if (firebaseUser) {
      navigate("/dashboard");
      return;
    }
    await handleAuthClick();
  };

  const currentRole = sampleRoles[selectedRoleIdx];

  return (
    <div className="min-h-screen bg-background selection:bg-primary/20 selection:text-primary relative overflow-hidden">
      
      {/* Dynamic Animated Neomorphic Background Orbs */}
      <motion.div 
        animate={{ y: [0, -25, 0], x: [0, 15, 0] }}
        transition={{ duration: 12, repeat: Infinity, ease: "easeInOut" }}
        className="fixed top-[-10%] left-[-5%] w-[45vw] h-[45vw] bg-primary/10 rounded-full blur-[140px] -z-10 pointer-events-none" 
      />
      <motion.div 
        animate={{ y: [0, 30, 0], x: [0, -20, 0] }}
        transition={{ duration: 15, repeat: Infinity, ease: "easeInOut" }}
        className="fixed bottom-[-10%] right-[-5%] w-[45vw] h-[45vw] bg-accent/10 rounded-full blur-[140px] -z-10 pointer-events-none" 
      />
      <div className="fixed inset-0 grid-pattern opacity-[0.1] -z-10 pointer-events-none" />

      {/* Neomorphic Navigation Bar */}
      <nav className="fixed top-0 w-full z-50 bg-background/90 backdrop-blur-xl shadow-neo-raised border-b border-border/40 transition-all duration-300">
        <div className="container mx-auto flex items-center justify-between h-16 px-4 sm:px-6">
          <motion.div 
            whileHover={{ scale: 1.02 }}
            className="flex items-center gap-3 cursor-pointer"
            onClick={() => navigate("/")}
          >
            <div className="h-10 w-10 rounded-xl bg-background shadow-neo-raised flex items-center justify-center border border-primary/30">
              <FileText className="h-5 w-5 text-primary" />
            </div>
            <span className="font-extrabold text-xl tracking-tight text-foreground">ResumeAI</span>
          </motion.div>
          
          <div className="flex items-center gap-3.5">
            <ThemeToggle className="h-10 w-10" />
            <Button 
              variant="ghost" 
              size="sm" 
              onClick={handleAuthClick} 
              disabled={loading} 
              className="hidden sm:flex shadow-neo-raised-sm hover:shadow-neo-raised font-medium h-10 px-4 rounded-xl"
            >
              Log in
            </Button>
            <Button 
              variant="hero" 
              size="sm" 
              onClick={handleGetStarted} 
              disabled={loading} 
              className="glow-primary font-medium h-10 px-5 rounded-xl active:scale-95 transition-transform"
            >
              Get Started
            </Button>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative pt-28 sm:pt-36 lg:pt-48 pb-20 sm:pb-28 overflow-hidden">
        <div className="container mx-auto px-4 sm:px-6 relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
            className="max-w-4xl mx-auto text-center flex flex-col items-center"
          >
            {/* Animated Neomorphic Pill Badge */}
            <motion.div 
              initial={{ scale: 0.85, opacity: 0 }} 
              animate={{ scale: 1, opacity: 1 }} 
              transition={{ delay: 0.2, type: "spring", stiffness: 200 }}
              whileHover={{ scale: 1.05 }}
              className="inline-flex items-center gap-2.5 px-5 py-2.5 rounded-full bg-background shadow-neo-pressed text-primary text-sm font-semibold mb-8 border border-primary/20 cursor-default"
            >
              <Sparkles className="h-4 w-4 text-primary animate-pulse" />
              <span>AI-Powered Resume Tailoring & Portfolio Deploy</span>
            </motion.div>
            
            {/* Hero Main Heading */}
            <h1 className="text-4xl sm:text-6xl md:text-7xl lg:text-8xl font-black tracking-tighter leading-[1.05] mb-8">
              <span className="text-foreground">Tailor Resumes.</span>
              <br />
              <span className="text-gradient bg-clip-text text-transparent">Deploy Portfolios.</span>
            </h1>
            
            <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-10 leading-relaxed font-medium">
              Upload your master profile, paste job requirements, and generate tailored resume PDFs plus Cloudflare portfolio sites in seconds.
            </p>
            
            {/* Hero Action Buttons */}
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 w-full sm:w-auto">
              <motion.div whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }} className="w-full sm:w-auto">
                <Button 
                  variant="hero" 
                  size="lg" 
                  className="w-full sm:w-auto text-base px-9 h-14 glow-strong rounded-2xl font-semibold shadow-neo-raised hover:shadow-neo-raised-lg transition-all" 
                  onClick={handleGetStarted} 
                  disabled={loading}
                >
                  Start Building Free <ArrowRight className="ml-2.5 h-5 w-5" />
                </Button>
              </motion.div>

              <motion.div whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }} className="w-full sm:w-auto">
                <Button 
                  variant="outline" 
                  size="lg" 
                  className="w-full sm:w-auto text-base px-9 h-14 bg-background shadow-neo-raised hover:shadow-neo-raised-lg border-border/50 text-foreground hover:text-primary rounded-2xl font-semibold transition-all"
                  onClick={handleGetStarted}
                >
                  View Interactive Demo
                </Button>
              </motion.div>
            </div>

            {/* Floating Interactive Neomorphic Preview Panel */}
            <motion.div 
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4, duration: 0.8 }}
              whileHover={{ y: -6 }}
              className="w-full max-w-3xl mt-16 p-6 sm:p-8 bg-card shadow-neo-raised-lg rounded-3xl border border-border/40 text-left relative overflow-hidden"
            >
              <div className="flex items-center justify-between border-b border-border/40 pb-4 mb-6">
                <div className="flex items-center gap-2">
                  <div className="w-3 h-3 rounded-full bg-rose-500/80 shadow-neo-raised-sm" />
                  <div className="w-3 h-3 rounded-full bg-amber-500/80 shadow-neo-raised-sm" />
                  <div className="w-3 h-3 rounded-full bg-emerald-500/80 shadow-neo-raised-sm" />
                  <span className="ml-2 text-xs font-mono text-muted-foreground">resume-ai-builder.v2</span>
                </div>
                <div className="flex items-center gap-1.5 text-xs text-primary font-semibold bg-background shadow-neo-pressed px-3 py-1 rounded-full border border-primary/20">
                  <ShieldCheck className="w-3.5 h-3.5" /> Ready to Tailor
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {steps.map((s) => (
                  <motion.div 
                    key={s.step}
                    whileHover={{ scale: 1.03 }}
                    className="p-4 bg-background shadow-neo-pressed rounded-2xl border border-border/30 flex flex-col justify-between"
                  >
                    <div className="flex items-center justify-between mb-3">
                      <span className="text-xs font-bold text-primary font-mono">{s.step}</span>
                      <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                    </div>
                    <div>
                      <h4 className="text-sm font-bold text-foreground mb-1">{s.title}</h4>
                      <p className="text-xs text-muted-foreground leading-relaxed">{s.desc}</p>
                    </div>
                  </motion.div>
                ))}
              </div>
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* Stats Counter Section */}
      <section className="py-16 relative z-10 border-y border-border/30 bg-background/50">
        <div className="container mx-auto px-4 sm:px-6">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 max-w-5xl mx-auto">
            {stats.map((st, i) => (
              <motion.div 
                key={st.label}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="bg-card shadow-neo-raised p-6 rounded-2xl border border-border/40 text-center flex flex-col items-center justify-center group hover:shadow-neo-raised-lg transition-all"
              >
                <div className="w-10 h-10 rounded-xl bg-background shadow-neo-pressed flex items-center justify-center mb-3 border border-primary/20 group-hover:scale-110 transition-transform">
                  <st.icon className="w-5 h-5 text-primary" />
                </div>
                <p className="text-2xl sm:text-3xl font-black text-foreground mb-1 tracking-tight">{st.value}</p>
                <p className="text-xs font-semibold text-muted-foreground">{st.label}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Interactive AI Keyword Match Simulator Section */}
      <section className="py-20 sm:py-28 relative z-10">
        <div className="container mx-auto px-4 sm:px-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-background shadow-neo-pressed text-primary text-xs font-bold mb-4 border border-primary/20">
              <Sliders className="w-3.5 h-3.5" /> Interactive Match Simulator
            </div>
            <h2 className="text-3xl md:text-5xl font-black mb-4 text-foreground tracking-tight">Test AI Tailoring Precision.</h2>
            <p className="text-muted-foreground text-lg max-w-xl mx-auto font-medium">
              Select a target career path to simulate how ResumeAI aligns your master profile keywords in real time.
            </p>
          </motion.div>

          <div className="max-w-4xl mx-auto bg-card shadow-neo-raised-lg rounded-3xl p-6 sm:p-10 border border-border/40">
            {/* Role Tabs */}
            <div className="flex flex-wrap gap-2.5 mb-8 justify-center">
              {sampleRoles.map((r, i) => (
                <button
                  key={r.role}
                  type="button"
                  onClick={() => setSelectedRoleIdx(i)}
                  className={`px-4 py-2.5 rounded-xl text-xs sm:text-sm font-bold transition-all duration-200 ${
                    selectedRoleIdx === i
                      ? "bg-background shadow-neo-pressed text-primary border border-primary/40 scale-105"
                      : "bg-background shadow-neo-raised text-muted-foreground hover:text-foreground border border-border/30"
                  }`}
                >
                  {r.role}
                </button>
              ))}
            </div>

            {/* Simulated Match Progress */}
            <div className="bg-background shadow-neo-pressed rounded-2xl p-6 border border-border/30 mb-8">
              <div className="flex items-center justify-between mb-3">
                <span className="text-sm font-semibold text-foreground">ATS Match Optimization Score</span>
                <span className="text-lg font-black text-primary font-mono">{currentRole.matchScore}% Match</span>
              </div>
              
              <div className="h-3 w-full bg-card shadow-neo-pressed rounded-full overflow-hidden p-0.5">
                <motion.div
                  key={selectedRoleIdx}
                  initial={{ width: "0%" }}
                  animate={{ width: `${currentRole.matchScore}%` }}
                  transition={{ duration: 0.8, ease: "easeOut" }}
                  className="h-full bg-gradient-to-r from-primary to-accent rounded-full shadow-neo-raised-sm"
                />
              </div>
            </div>

            {/* Dynamic Keywords Tag Cloud */}
            <div>
              <p className="text-xs uppercase tracking-wider font-bold text-muted-foreground mb-4">Auto-Extracted High-Impact Keywords</p>
              <div className="flex flex-wrap gap-2.5">
                <AnimatePresence mode="popLayout">
                  {currentRole.keywords.map((kw, idx) => (
                    <motion.span
                      key={kw}
                      initial={{ opacity: 0, scale: 0.8 }}
                      animate={{ opacity: 1, scale: 1 }}
                      transition={{ delay: idx * 0.06 }}
                      className="px-3.5 py-1.5 rounded-xl text-xs font-semibold bg-background shadow-neo-raised text-foreground border border-primary/20 flex items-center gap-1.5"
                    >
                      <CheckCircle2 className="w-3.5 h-3.5 text-primary" /> {kw}
                    </motion.span>
                  ))}
                </AnimatePresence>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Grid Section */}
      <section className="py-20 sm:py-28 relative z-10">
        <div className="container mx-auto px-4 sm:px-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="text-center mb-16"
          >
            <h2 className="text-3xl md:text-5xl font-black mb-4 text-foreground tracking-tight">Everything you need to stand out.</h2>
            <p className="text-muted-foreground text-lg max-w-xl mx-auto font-medium">
              Intelligent resume parsing, automated tailoring, and instant Cloudflare portfolio publishing.
            </p>
          </motion.div>

          <motion.div 
            variants={containerVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-80px" }}
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 sm:gap-8 max-w-6xl mx-auto"
          >
            {features.map((f) => (
              <motion.div
                key={f.title}
                variants={cardVariants}
                whileHover={{ y: -8, scale: 1.02 }}
                className="group bg-card shadow-neo-raised hover:shadow-neo-raised-lg p-8 rounded-3xl border border-border/40 transition-all duration-300 relative overflow-hidden flex flex-col justify-between"
              >
                <div>
                  <div className="h-14 w-14 rounded-2xl bg-background shadow-neo-pressed group-hover:shadow-neo-raised flex items-center justify-center mb-6 border border-primary/20 transition-all duration-300">
                    <f.icon className="h-7 w-7 text-primary group-hover:scale-110 transition-transform" />
                  </div>
                  <h3 className="text-xl font-bold text-foreground mb-3 tracking-tight">{f.title}</h3>
                  <p className="text-muted-foreground leading-relaxed text-sm font-medium">{f.desc}</p>
                </div>
                
                <div className="mt-6 pt-4 border-t border-border/20 flex items-center text-xs font-semibold text-primary opacity-0 group-hover:opacity-100 transition-opacity">
                  Learn more <ArrowRight className="w-3.5 h-3.5 ml-1 group-hover:translate-x-1 transition-transform" />
                </div>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Neomorphic FAQ Accordion Section */}
      <section className="py-20 sm:py-28 relative z-10 bg-background/40">
        <div className="container mx-auto px-4 sm:px-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-3xl md:text-5xl font-black mb-4 text-foreground tracking-tight">Frequently Asked Questions</h2>
            <p className="text-muted-foreground text-lg max-w-xl mx-auto font-medium">
              Everything you need to know about tailoring resumes and publishing Cloudflare portfolios.
            </p>
          </motion.div>

          <div className="max-w-3xl mx-auto space-y-4">
            {faqs.map((faq, idx) => {
              const isOpen = openFaqIdx === idx;

              return (
                <motion.div
                  key={faq.q}
                  initial={{ opacity: 0, y: 15 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: idx * 0.08 }}
                  className="bg-card shadow-neo-raised rounded-2xl border border-border/40 overflow-hidden"
                >
                  <button
                    type="button"
                    onClick={() => setOpenFaqIdx(isOpen ? null : idx)}
                    className="w-full px-6 py-5 flex items-center justify-between text-left font-bold text-foreground hover:text-primary transition-colors gap-4"
                  >
                    <span>{faq.q}</span>
                    <div className={`w-8 h-8 rounded-xl bg-background shadow-neo-pressed flex items-center justify-center shrink-0 transition-transform duration-300 ${isOpen ? "rotate-180 text-primary" : "text-muted-foreground"}`}>
                      <ChevronDown className="w-4 h-4" />
                    </div>
                  </button>

                  <AnimatePresence>
                    {isOpen && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: "auto", opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.3 }}
                        className="overflow-hidden"
                      >
                        <div className="px-6 pb-6 pt-1 text-sm text-muted-foreground leading-relaxed border-t border-border/20 mt-1">
                          {faq.a}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Unique Neomorphic Call To Action (CTA) Section */}
      <section className="py-20 sm:py-28 relative z-10">
        <div className="container mx-auto px-4 sm:px-6">
          <motion.div 
            initial={{ opacity: 0, scale: 0.94 }} 
            whileInView={{ opacity: 1, scale: 1 }} 
            viewport={{ once: true }} 
            transition={{ duration: 0.7 }}
            className="relative bg-card shadow-neo-raised-lg rounded-3xl border border-primary/30 p-8 sm:p-12 md:p-20 text-center overflow-hidden max-w-5xl mx-auto"
          >
            <div className="absolute top-0 right-0 w-80 h-80 bg-primary/10 rounded-full blur-[100px] pointer-events-none" />
            <div className="absolute bottom-0 left-0 w-80 h-80 bg-accent/10 rounded-full blur-[100px] pointer-events-none" />
            
            <div className="relative z-10 flex flex-col items-center">
              <motion.div 
                whileHover={{ rotate: 180 }} 
                transition={{ duration: 0.6 }}
                className="w-16 h-16 rounded-2xl bg-background shadow-neo-raised flex items-center justify-center mb-8 border border-primary/30"
              >
                <Sparkles className="w-8 h-8 text-primary" />
              </motion.div>
              
              <h2 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-black mb-6 text-foreground tracking-tight">Ready to elevate your career?</h2>
              <p className="text-muted-foreground text-lg sm:text-xl max-w-2xl mx-auto mb-10 leading-relaxed font-medium">
                Build your master profile once, tailor for every opportunity with AI precision, and deploy live portfolios in one workflow.
              </p>
              
              <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
                <Button 
                  variant="hero" 
                  size="lg" 
                  className="text-lg px-12 h-16 glow-strong rounded-full shadow-neo-raised hover:shadow-neo-raised-lg transition-all" 
                  onClick={handleGetStarted} 
                  disabled={loading}
                >
                  Get Started for Free <ArrowRight className="ml-2.5 h-6 w-6" />
                </Button>
              </motion.div>
              
              <p className="text-xs text-muted-foreground mt-6 font-semibold tracking-wide uppercase">
                No credit card required • Fast Google Single Sign-On
              </p>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Neomorphic Footer */}
      <footer className="border-t border-border/30 bg-background shadow-neo-raised relative z-10 py-10">
        <div className="container mx-auto px-4 sm:px-6 flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2.5 text-foreground font-extrabold text-lg">
            <div className="h-8 w-8 rounded-xl bg-background shadow-neo-raised flex items-center justify-center border border-primary/20">
              <FileText className="h-4 w-4 text-primary" />
            </div>
            ResumeAI
          </div>
          <div className="text-xs text-muted-foreground font-semibold">
            © {new Date().getFullYear()} ResumeAI. Crafted with Neomorphism & Framer Motion.
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Landing;